CREATE TABLE packages (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
	,packageNumber VARCHAR NOT NULL UNIQUE
	,courierName VARCHAR NOT NULL
	,courierCode VARCHAR NOT NULL
	,addDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,lastUpdate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,monitor INTEGER NOT NULL DEFAULT 0
	,HASH VARCHAR DEFAULT NULL
	,DESC VARCHAR DEFAULT NULL
	)